version: "3.9"
services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
